import streamlit as st
import pickle
from datetime import datetime

# Load Model
model = pickle.load(open("model.pkl", "rb"))
scaler = pickle.load(open("scaler.pkl", "rb"))

# Page Config
st.set_page_config(
    page_title="Heart Disease Prediction",
    page_icon="❤️",
    layout="wide"
)

# ================= CSS =================

st.markdown("""
<style>

.stApp{
background: linear-gradient(to right,#f8f9ff,#eef3ff);
}

.title{
text-align:center;
font-size:50px;
font-weight:bold;
color:#1f2a56;
padding:10px;
}

.card{
background:white;
padding:20px;
border-radius:15px;
box-shadow:0px 4px 15px rgba(0,0,0,0.1);
margin-bottom:20px;
}

.health-tip{
background:#e9fff0;
padding:15px;
border-radius:10px;
font-size:18px;
color:#146c43;
margin-top:20px;
}

.result-card{
background:white;
padding:20px;
border-radius:15px;
box-shadow:0px 4px 15px rgba(0,0,0,0.1);
}

</style>
""", unsafe_allow_html=True)

# ================= SIDEBAR =================

with st.sidebar:

    st.title("❤️ HDPS")

    st.markdown("---")

    st.info("AI Powered Heart Disease Prediction System")

    st.metric("Model Accuracy", "88.7%")

    st.markdown("---")

    st.success("✔ Secure")
    st.success("✔ Fast Prediction")
    st.success("✔ Accurate Results")

    st.markdown("---")

    st.subheader("About")

    st.write("""
Heart Disease Prediction System uses
Machine Learning to predict whether
a patient is at risk of heart disease.
""")

# ================= HEADER =================

st.markdown("""
<div class='title'>
❤️ Heart Disease Prediction System
</div>
""", unsafe_allow_html=True)

st.write("### Enter Patient Details")

# ================= FORM =================

col1, col2 = st.columns(2)

with col1:

    age = st.number_input("Age", 1, 120, 40)

    sex = st.selectbox(
        "Gender",
        [0,1],
        format_func=lambda x: "Female" if x==0 else "Male"
    )

    cp = st.selectbox(
        "Chest Pain Type",
        [0,1,2,3]
    )

    trestbps = st.number_input(
        "Resting Blood Pressure",
        80,250,120
    )

    chol = st.number_input(
        "Cholesterol",
        100,600,200
    )

    fbs = st.selectbox(
        "Fasting Blood Sugar",
        [0,1]
    )

with col2:

    restecg = st.selectbox(
        "Rest ECG",
        [0,1,2]
    )

    thalach = st.number_input(
        "Max Heart Rate",
        50,250,150
    )

    exang = st.selectbox(
        "Exercise Angina",
        [0,1]
    )

    oldpeak = st.number_input(
        "Old Peak",
        0.0,10.0,1.0
    )

    slope = st.selectbox(
        "Slope",
        [0,1,2]
    )

    ca = st.selectbox(
        "Major Vessels",
        [0,1,2,3,4]
    )

    thal = st.selectbox(
        "Thal",
        [0,1,2,3]
    )

# ================= PREDICT =================

if st.button(
    "🔍 Predict Heart Disease",
    use_container_width=True
):

    data = [[
        age,
        sex,
        cp,
        trestbps,
        chol,
        fbs,
        restecg,
        thalach,
        exang,
        oldpeak,
        slope,
        ca,
        thal
    ]]

    scaled_data = scaler.transform(data)

    prediction = model.predict(scaled_data)

    probability = model.predict_proba(
        scaled_data
    )[0][1]

    st.markdown("---")

    st.subheader("Prediction Result")

    if prediction[0] == 1:

        st.error(
            "⚠ Heart Disease Risk Detected"
        )

        result = "Heart Disease Risk Detected"

    else:

        st.success(
            "✅ No Heart Disease Detected"
        )

        result = "No Heart Disease Detected"

    # Risk Meter

    st.subheader("Risk Probability")

    st.progress(
        int(probability * 100)
    )

    st.write(
        f"### {probability*100:.2f}% Risk"
    )

    # Analytics

    st.subheader("📊 Health Analytics")

    c1,c2,c3 = st.columns(3)

    with c1:
        st.metric(
            "Blood Pressure",
            trestbps
        )

    with c2:
        st.metric(
            "Cholesterol",
            chol
        )

    with c3:
        st.metric(
            "Heart Rate",
            thalach
        )

    # Recommendations

    st.markdown("""
    <div class='card'>
    <h3>💡 Health Recommendations</h3>

    ✔ Exercise Daily<br>
    ✔ Eat Healthy Diet<br>
    ✔ Reduce Stress<br>
    ✔ Avoid Smoking<br>
    ✔ Regular Checkups<br>

    </div>
    """, unsafe_allow_html=True)

    # Report

    report = f"""
HEART DISEASE PREDICTION REPORT

Date: {datetime.now()}

Age: {age}
Gender: {"Male" if sex==1 else "Female"}

Blood Pressure: {trestbps}

Cholesterol: {chol}

Heart Rate: {thalach}

Prediction Result:
{result}

Risk Probability:
{probability*100:.2f}%

Generated By:
Heart Disease Prediction System
"""

    st.download_button(
        "📄 Download Report",
        report,
        file_name="Heart_Report.txt"
    )

# ================= FOOTER =================

st.markdown("""
<div class='health-tip'>
🍀 Health Tip:
Exercise regularly, maintain a healthy diet,
sleep well and avoid smoking to keep your heart healthy.
</div>
""", unsafe_allow_html=True)